version: '3.8'

services:
  mongodb:
    image: mongo:5.0
    container_name: emathsci-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: e-math-sci-school
    volumes:
      - mongodb_data:/data/db
      - ./database/init:/docker-entrypoint-initdb.d
    networks:
      - emathsci-network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: emathsci-backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://admin:password123@mongodb:27017/e-math-sci-school?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-change-in-production
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - mongodb
    volumes:
      - ./backend/uploads:/app/uploads
      - ./logs:/app/logs
    networks:
      - emathsci-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: emathsci-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      REACT_APP_API_URL: http://localhost:5000/api
      REACT_APP_NAME: E-Math-Sci School
    depends_on:
      - backend
    networks:
      - emathsci-network

  nginx:
    image: nginx:alpine
    container_name: emathsci-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    networks:
      - emathsci-network

volumes:
  mongodb_data:

networks:
  emathsci-network:
    driver: bridge
